// AerisGo Flight Numbers
export const FLIGHT_NUMBERS = [
  "AG101",
  "AG102",
  "AG103",
  "AG104",
  "AG105",
  "AG106",
  "AG107",
  "AG108",
  "AG109",
  "AG110",
  "AG201",
  "AG202",
  "AG203",
  "AG204",
  "AG205",
  "AG206",
  "AG207",
  "AG208",
  "AG209",
  "AG210",
  "AG301",
  "AG302",
  "AG303",
  "AG304",
  "AG305",
  "AG306",
  "AG307",
  "AG308",
  "AG309",
  "AG310",
  "AG401",
  "AG402",
  "AG403",
  "AG404",
  "AG405",
  "AG406",
  "AG407",
  "AG408",
  "AG409",
  "AG410",
  "AG501",
  "AG502",
  "AG503",
  "AG504",
  "AG505",
  "AG506",
  "AG507",
  "AG508",
  "AG509",
  "AG510",
];

// Indian Cities
export const INDIAN_LOCATIONS = [
  // Major Metro Cities
  "Mumbai, India",
  "Delhi, India",
  "Bangalore, India",
  "Hyderabad, India",
  "Chennai, India",
  "Kolkata, India",
  "Pune, India",
  "Ahmedabad, India",

  // State Capitals and Major Cities
  "Jaipur, India",
  "Lucknow, India",
  "Chandigarh, India",
  "Bhopal, India",
  "Patna, India",
  "Thiruvananthapuram, India",
  "Kochi, India",
  "Guwahati, India",
  "Bhubaneswar, India",
  "Ranchi, India",
  "Raipur, India",
  "Indore, India",
  "Nagpur, India",
  "Surat, India",
  "Vadodara, India",
  "Coimbatore, India",
  "Visakhapatnam, India",
  "Vijayawada, India",
  "Amritsar, India",
  "Varanasi, India",
  "Agra, India",
  "Goa, India",
  "Srinagar, India",
  "Jammu, India",
  "Dehradun, India",
  "Shimla, India",
  "Imphal, India",
  "Shillong, India",
  "Aizawl, India",
  "Kohima, India",
  "Agartala, India",
  "Gangtok, India",
  "Itanagar, India",
  "Dispur, India",
  "Panaji, India",
  "Port Blair, India",
];
